name: scav
description: SCAV
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  vrouter: ^1.2.1
  responsive_sizer: ^3.1.1
  provider: ^6.0.5
  datetime_picker_formfield_new: ^2.1.0
  intl: ^0.18.0
  custom_searchable_dropdown: ^2.1.1
  file_picker: ^6.1.1
  http_parser: ^4.0.2
  dio: ^5.3.2
  achievement_view: ^1.0.1
  cooky: ^2.0.0
  url_launcher: ^6.1.14
  dropdown_textfield: ^1.0.8
  animated_toggle_switch: ^0.8.0
  custom_dropdown_2: ^1.0.2
  syncfusion_flutter_pdf: ^24.1.41
  material_loading_buttons: ^1.1.0
  aligned_dialog: ^0.0.7
  path_provider: ^2.1.1
  open_file: ^3.3.2
  universal_html: ^2.2.4
  flutter_excel: ^1.0.1
  lite_rolling_switch: ^1.0.1
  sweet_cookie: ^0.0.5



  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/fondo_rojo.png
    - assets/images/leyenda_instituto.png
    - assets/images/logo_artesanias.png
    - assets/images/pleca_x.png
    - assets/images/portada_home.jpg
    - assets/images/ORGANIZACION_INFORMACION-03.png
    - assets/images/ORGANIZACION_INFORMACION-04.png
    - assets/images/ORGANIZACION_INFORMACION-05.png
    - assets/images/ORGANIZACION_INFORMACION-06.png
    - assets/images/ORGANIZACION_INFORMACION-07.png
    - assets/images/ORGANIZACION_INFORMACION-08.png
    - assets/images/ORGANIZACION_INFORMACION-09.png
    - assets/images/ORGANIZACION_INFORMACION-10.png
    - assets/images/LOGO.png
    - assets/images/PLECA_ROJA-03.png
    - assets/images/LATERAL.png
    - assets/images/x.png
    - assets/images/xx.png
    - assets/images/cargando.gif
    - assets/images/loading_request.gif
    - assets/images/credencial.png
    - assets/images/credencial.jpg
    - assets/images/credencial_1.jpg
    - assets/images/credencial_texto.jpg
    - assets/pdf/credencial_img_individual.pdf
    - assets/pdf/credencial_img_org.pdf
    - assets/pdf/credencial_individual.pdf
    - assets/pdf/credencial_org.pdf
    - assets/pdf/constancia.pdf
    - assets/pdf/CONSTANCIA_GENERICO_VERSION1.pdf
    - assets/pdf/CONSTANCIA_GENERICO_VERSION2.pdf
    - assets/pdf/CONSTANCIA_GENERICO_VERSION3.pdf
